#!/usr/bin/env python3
"""Generate the CUSTODIAN LICENCE catalog — the plans a RESELLER is charged.

WHY THIS EXISTS
---------------
`catalog/custodian-catalog.xml` holds the three RETAIL plans (basic/pro/business),
i.e. what the reseller charges THEIR customers. Under Model B the reseller also pays
**us** a licence, and until now **no licence plan existed anywhere** — so there was
nothing to invoice a reseller from. `features/domain-email-and-go-to-market-strategy.md`
§1.3 records this as a hard blocker; §6 of the pricing doc records it as the single
missing input.

TWO CATALOGS, NOT ONE
---------------------
    our tenant's catalog      <- THIS FILE   the reseller pays US the licence
    the reseller's tenant     <- custodian-catalog.xml   their customers pay THEM

WHAT IS LOCKED vs WHAT IS NOT
-----------------------------
Locked (`pricing/reseller-pricing-model.md`, LOCKED 2026-09-28):

    Monthly       x1.35
    Quarterly     x1.40
    Semi-annual   x1.40    (dropped from x1.45 so the ladder stops running backwards)
    Annual        x1.40

NOT locked — and the reason this script refuses to run without it
(`pricing/reseller-pricing-model.md` §5): the operating base is "server ($5-6) +
token cost", where the server part is FIXED and the token part is VARIABLE. A fixed
monthly fee cannot cleanly include a variable cost, so the intended shape is
"baseline plan + pay-as-you-go overage" — but the **baseline token allotment per
cycle is unconfirmed**. Hence `--server-cost` and `--baseline-tokens` are REQUIRED and
have no defaults: a guessed price must not be able to reach the billing engine.

NO RELOAD PLAN HERE — deliberately
----------------------------------
Earlier drafts said our catalog must hold "4 frequencies + a reload product". Superseded:
a top-up is an arbitrary, one-time amount (min $10, no max), which a catalog plan cannot
express. It is an **EXTERNAL CHARGE** carrying `CUSTODIAN_TOPUP` in itemDetails (see
`kb-bridge/README.md` and `kb_bridge.py run_topup`). Adding a reload plan would create a
second, contradictory mechanism.

USAGE
-----
    python3 catalog/make-licence-catalog.py --server-cost 6.00 --baseline-tokens 0 \\
        --token-cost 1.50 > /tmp/licence-catalog.xml

    # validate WITHOUT uploading (definitive):
    curl ... -X POST .../1.0/kb/catalog/xml/validate -H 'Content-Type: text/xml' \\
         --data-binary @/tmp/licence-catalog.xml
"""
import argparse
import sys

# LOCKED 2026-09-28 (pricing/reseller-pricing-model.md). Do not edit without the
# pricing doc changing first — this ladder IS the margin.
#
# NOTE on the period names: these must be exact Kill Bill `BillingPeriod` enum values.
# There is NO `SEMI_ANNUAL` in that enum — semi-annual is `BIANNUAL` (= Period.months(6)).
# Verified against killbill-api BillingPeriod.java (2026-09-30). An earlier revision of this
# generator emitted `SEMI_ANNUAL`, which Kill Bill would have rejected at upload.
LADDER = [
    ("monthly", "MONTHLY", 1.35),
    ("quarterly", "QUARTERLY", 1.40),
    ("semiannual", "BIANNUAL", 1.40),
    ("annual", "ANNUAL", 1.40),
]

PRODUCT = "custodian-licence"

HEADER = """<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  GENERATED by catalog/make-licence-catalog.py — DO NOT EDIT BY HAND.
  Edit the generator (the ladder and the shape) or the pricing doc (the numbers).

  The LICENCE a RESELLER pays us. The retail plans their customers pay THEM live in
  catalog/custodian-catalog.xml, on the reseller's own tenant.

  Base used: server ${server:.2f} + baseline tokens ${tokens:.2f} = ${base:.2f} per cycle
  (baseline units {btokens:g} at ${tcost:.2f}/unit)

  Margin ladder (LOCKED 2026-09-28, pricing/reseller-pricing-model.md):
    monthly x1.35 | quarterly x1.40 | semi-annual x1.40 | annual x1.40

  No reload plan: a top-up is an EXTERNAL CHARGE, not a catalog plan.

  NOTE: XML comments must not contain a double hyphen. Use an em-dash, as above and
  below. Kill Bill's validator rejects the whole catalog with the error
  "The string (double hyphen) is not permitted within comments." and still answers
  HTTP 200, so check the response BODY, not the status code.
-->
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://docs.killbill.io/latest/catalog.xsd">

  <effectiveDate>{effective}</effectiveDate>
  <catalogName>CustodianLicenceCatalog</catalogName>
  <recurringBillingMode>IN_ADVANCE</recurringBillingMode>

  <currencies>
    <currency>USD</currency>
  </currencies>

  <units>
  </units>

  <products>
    <product name="{product}">
      <category>BASE</category>
    </product>
  </products>

  <rules>
    <changePolicy>
      <changePolicyCase>
        <policy>IMMEDIATE</policy>
      </changePolicyCase>
    </changePolicy>
    <cancelPolicy>
      <cancelPolicyCase>
        <policy>IMMEDIATE</policy>
      </cancelPolicyCase>
    </cancelPolicy>
  </rules>

  <plans>
"""

PLAN = """
    <!-- licence-{key} — base ${base:.2f} x {mult:.2f} = ${price:.2f} / {period} -->
    <plan name="licence-{key}">
      <product>{product}</product>
      <recurringBillingMode>IN_ADVANCE</recurringBillingMode>
      <initialPhases>
      </initialPhases>
      <finalPhase type="EVERGREEN">
        <duration>
          <unit>UNLIMITED</unit>
        </duration>
        <recurring>
          <billingPeriod>{period}</billingPeriod>
          <recurringPrice>
            <price>
              <currency>USD</currency>
              <value>{price:.2f}</value>
            </price>
          </recurringPrice>
        </recurring>
      </finalPhase>
    </plan>
"""

FOOTER = """
  </plans>

  <priceLists>
    <defaultPriceList name="DEFAULT">
      <plans>
{plan_refs}      </plans>
    </defaultPriceList>
  </priceLists>

</catalog>
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--server-cost", type=float, required=True,
                    help="REQUIRED. Monthly server cost per reseller, e.g. 6.00. "
                         "No default: pricing/reseller-pricing-model.md section 5 says "
                         "the base is unresolved, so a guessed number must not ship.")
    ap.add_argument("--baseline-tokens", type=float, required=True,
                    help="REQUIRED. Token UNITS included per cycle. Use 0 for the "
                         "server-only model (all tokens then arrive as reloads).")
    ap.add_argument("--token-cost", type=float, default=1.50,
                    help="Our COST per baseline token unit (default 1.50 = 1M tokens "
                         "at the pinned DeepSeek PRO peak rate). Only used when "
                         "--baseline-tokens > 0.")
    ap.add_argument("--effective", default="2026-10-01T00:00:00+00:00",
                    help="Catalog effective date. Defaults to the 1st so it aligns "
                         "with the period anchor the bridge resets on.")
    ap.add_argument("--out", default="-", help="Output path, or - for stdout.")
    a = ap.parse_args()

    if a.server_cost <= 0:
        print("refusing: --server-cost must be > 0", file=sys.stderr)
        return 2
    if a.baseline_tokens < 0:
        print("refusing: --baseline-tokens cannot be negative", file=sys.stderr)
        return 2

    token_part = a.baseline_tokens * a.token_cost
    base = a.server_cost + token_part

    body = [HEADER.format(server=a.server_cost, tokens=token_part, base=base,
                          btokens=a.baseline_tokens, tcost=a.token_cost,
                          effective=a.effective, product=PRODUCT)]
    for key, period, mult in LADDER:
        body.append(PLAN.format(key=key, period=period, mult=mult, base=base,
                                price=base * mult, product=PRODUCT))
    refs = "".join(f"        <plan>licence-{k}</plan>\n" for k, _, _ in LADDER)
    body.append(FOOTER.format(plan_refs=refs))
    xml = "".join(body)

    if a.out == "-":
        sys.stdout.write(xml)
    else:
        with open(a.out, "w") as fh:
            fh.write(xml)

    print("", file=sys.stderr)
    print("base per cycle : ${:.2f}  (server ${:.2f} + tokens ${:.2f})".format(
        base, a.server_cost, token_part), file=sys.stderr)
    print("  {:<12} {:<8} {:>6}  {:>10}  {:>10}".format(
        "plan", "period", "mult", "price", "our margin"), file=sys.stderr)
    for key, period, mult in LADDER:
        price = base * mult
        print("  licence-{:<4} {:<8} {:>6.2f}  {:>10.2f}  {:>10.2f}".format(
            key, period, mult, price, price - base), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
